build(pyenv) - Fully configure pyenv to work
Unfortunately, we were not adding `eval "$(pyenv init -)"` into a developer's
shell start up configuration file, thus, `pyenv` would be available as a command yet
not changing the Python version based on `.python-version`.

This also moves pyenv logic into its own script.

diff --git a/.github/workflows/development-environment.yml b/.github/workflows/development-environment.yml
--- a/.github/workflows/development-environment.yml
+++ b/.github/workflows/development-environment.yml
@@ -26,9 +26,8 @@ jobs:
         shell: bash
         run: |
           echo "HOMEBREW_CACHE=`brew --cache`" >> $GITHUB_ENV
-          echo "PYENV_ROOT=$HOME/.pyenv" >> $GITHUB_ENV
           echo "VOLTA_HOME=$HOME/.volta" >> $GITHUB_ENV
-          echo "PATH=$HOME/.pyenv/shims:$HOME/.volta/bin:$PATH" >> $GITHUB_ENV
+          echo "PATH=$HOME/.volta/bin:$PATH" >> $GITHUB_ENV
 
       - name: Cache (brew)
         uses: actions/cache@v2
@@ -52,12 +51,12 @@ jobs:
       - name: Install Python (via Pyenv)
         id: python-version
         shell: bash
-        # XXX: Locally, pyenv makes 3.6.10 be the selected version in use,
-        # however, in here it selects /usr/local/bin/python. I'm using `pyenv global` to work around it
         # XXX: Can we cache the installed Python environments?
         run: |
           make setup-pyenv
-          pyenv global 3.6.10
+          source "$HOME/.bashrc"
+          [[ $(which python) == /usr/bin/python ]] && echo "It fails to set correct Python" && exit 1
+          env | grep TERM
           echo "::set-output name=python-version::$(python -V  | sed s/Python\ //g)"
 
       - name: Setup pip
@@ -75,9 +74,18 @@ jobs:
             ${{ runner.os }}-pip-py${{ steps.python-version.outputs.python-version }}
 
       - name: Set up development environment (as per docs)
+        # XXX: It's unfortunate we need to call pyenv init - to make the Python version be switched correctly
+        # TODO: Upstream installing wheel to bootstrap-sentry
         run: |
+          env | grep TERM
+          python -V
+          source "$HOME/.bashrc"
+          python -V
+          eval "$(pyenv init -)"
+          python -V
           python -m venv .venv
           source .venv/bin/activate
+          pip install wheel
           make install-py-dev
           make setup-git
           curl https://get.volta.sh | bash
